### ISSUE TITLE
Could not apply permission mask

### ISSUE THREAD

**Issue by elbakai** [croogo/croogo#752]
Hello;

when i check my log file, always i found this error **Could not apply permission mask**, i make:
tmp folder's permission : 777
i put `'mask' => 0777``in **Config/croogo.php** file
also i add` 'mask' => 0777` in **Vendor/croogo/croogo/Croogo/Config/croogo_bootstrap.ph**p
and also i found the some error.

What i can do to prevent this error ?

thanks

```
2016-03-03 20:40:12 Warning: Warning (512): Could not apply permission mask "..../public_html/tmp/cache/queries/settings/my_app_event_handlers" on cache file "438" in [..../public_html/Vendor/cakephp/cakephp/lib/Cake/Cache/Engine/FileEngine.php, line 364]
Trace:
FileEngine::_setKey() - APP/Vendor/cakephp/cakephp/lib/Cake/Cache/Engine/FileEngine.php, line 364
FileEngine::write() - APP/Vendor/cakephp/cakephp/lib/Cake/Cache/Engine/FileEngine.php, line 116
Cache::write() - APP/Vendor/cakephp/cakephp/lib/Cake/Cache/Cache.php, line 317
CroogoEventManager::loadListeners() - APP/Vendor/croogo/croogo/Croogo/Event/CroogoEventManager.php, line 80
require_once - APP/Vendor/croogo/croogo/Croogo/Config/croogo_bootstrap.php, line 138
include - APP/Vendor/croogo/croogo/Croogo/Config/bootstrap.php, line 8
CakePlugin::_includeFile() - APP/Vendor/cakephp/cakephp/lib/Cake/Core/CakePlugin.php, line 247
CakePlugin::bootstrap() - APP/Vendor/cakephp/cakephp/lib/Cake/Core/CakePlugin.php, line 167
CakePlugin::load() - APP/Vendor/cakephp/cakephp/lib/Cake/Core/CakePlugin.php, line 99
include - APP/Config/bootstrap.php, line 78
Configure::bootstrap() - APP/Vendor/cakephp/cakephp/lib/Cake/Core/Configure.php, line 92
include - APP/Vendor/cakephp/cakephp/lib/Cake/bootstrap.php, line 175
[main] - APP/webroot/index.php, line 90
```

**Comment by PaulPrecept** [comment]
I'm currently having this problem with Croogo 2.3.2 with the ../public_html/tmp/cache/settings/croogo_event_handlers file.

My server runs everything as the user/group that owns the website's files so permissions should never be a problem.

Any ideas how I can resolve this?

**Comment by miketallroth** [comment]
Not sure this will fix your problem, but I've seen a couple of less obvious situations that cause this problem.

If you run a cake shell from the command line as yourself, and it happens to touch a cache file, it will set permissions which are probably incompatible with apache. You need to make sure you either run the shell as the apache user, or clear out any files you touched when you're done running the shells.

Another related situation is if you run any cake shells via a cron job, the cron job must also use the same user:group as your apache server so that any files created by the shell have permissions compatible with apache. I had originally been running the cron as root (which is typical), so the cache files it created had root:root, and then when apache tried to access those files, it would throw perms errors.

Can you confirm the ownership of the exact file it is flagging at the point of the failure? In the situations I'm describing here, your tmp/cache directory will have different files with different ownership. Some will be from apache, others from you (running a shell) or your cron owner (probably root).

**Comment by PaulPrecept** [comment]
Will double-check and update this thread, but certain we're seeing this on sites that are not running cronjobs/shells and even if we are running them, they run as the website owner/group on our server.

If I manually run a cronjob as root, I would instantly see a huge number of problems with multiple cache file permissions updated, but this is a sporadic issue only affecting the ../public_html/tmp/cache/settings/croogo_event_handlers file that corrects itself on refreshing the page.

**Comment by rchavik** [comment]
Not applicable for >3.x.

For cache, suggest to use redis.
