### ISSUE TITLE
Pagination of nodes in term function of main NodesController

### ISSUE THREAD

**Issue by slightlychilled** [croogo/croogo#822]
Would it be possible to modify the term function in the main NodesController to allow the nodes to be ordered by an associated table?

**Comment by rchavik** [comment]
Not easily. You can attach a component to `NodesController` and try modify the retrieved results or attach a `Behavior` to the `Nodes` model. Either way is not very clean. It will be easier to directly modify `NodesController` in this case.

**Comment by slightlychilled** [comment]
Hi Rachman.
Thanks for the info. Updating the NodesController would be fine for me, but do you know how? I have tried several ways and cannot seem to get it to work.

**Comment by rchavik** [comment]
You need change the code somewhere around [here](https://github.com/croogo/croogo/blob/master/Nodes/Controller/NodesController.php#L542)

The actual pagination call is [here](https://github.com/croogo/croogo/blob/master/Nodes/Controller/NodesController.php#L602).  So you can do: `$this->log($this->paginate);` just before the `$this->paginate()` call so that you can see what is the used configuration.

**Comment by slightlychilled** [comment]
Hi
Thanks for the pointers. Do you have any idea how to use the cakephp pagination helper to order the parent on an associated table as I am yet to find a solution. I have seen details around using virtual tables, but cakephp states that this cannot be used to order the results. I am a little stuck.
